#!/usr/bin/env node

const { spawnSync } = require('node:child_process');
const path = require('node:path');

const cli = path.join(__dirname, '..', 'node_modules', '@commitlint', 'cli', 'cli.js');
const result = spawnSync(process.execPath, [cli, '--edit', process.argv[2]], { stdio: 'inherit' });

process.exit(result.status ?? 1);
